# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'claimlens_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['claimlens-api:8000']  # Docker service name
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
